from django.core.management.base import BaseCommand

from shop.models import Category, Product


class Command(BaseCommand):
    help = "Seed the development database with premium PC component demo products."

    def handle(self, *args, **options):
        Product.objects.all().delete()
        Category.objects.all().delete()

        categories = {
            "graphics_cards": Category.objects.get_or_create(
                name="Graphics Cards",
                slug="graphics-cards",
                defaults={"description": "High-performance GPUs for gaming, rendering, and AI workloads."},
            )[0],
            "memory": Category.objects.get_or_create(
                name="RAM",
                slug="ram",
                defaults={"description": "Fast DDR5 memory kits for gaming and creator builds."},
            )[0],
            "processors": Category.objects.get_or_create(
                name="Processors",
                slug="processors",
                defaults={"description": "Desktop CPUs for speed, efficiency, and multitasking."},
            )[0],
            "motherboards": Category.objects.get_or_create(
                name="Motherboards",
                slug="motherboards",
                defaults={"description": "Feature-rich boards with modern chipsets and expansion."},
            )[0],
            "storage": Category.objects.get_or_create(
                name="Storage",
                slug="storage",
                defaults={"description": "NVMe SSDs and drives for fast boot and load times."},
            )[0],
            "power_cooling": Category.objects.get_or_create(
                name="Power & Cooling",
                slug="power-cooling",
                defaults={"description": "Reliable PSUs, liquid coolers, and airflow essentials."},
            )[0],
            "cases": Category.objects.get_or_create(
                name="Cases",
                slug="cases",
                defaults={"description": "Showcase PC cases with airflow, glass, and clean cable paths."},
            )[0],
            "peripherals": Category.objects.get_or_create(
                name="Peripherals",
                slug="peripherals",
                defaults={"description": "Keyboards, mice, monitors, and build-ready desk gear."},
            )[0],
        }

        products = [
            {
                "category": categories["graphics_cards"],
                "name": "Neo RTX 4080 Dragon OC",
                "slug": "neo-rtx-4080-dragon-oc",
                "tagline": "16GB GDDR6X graphics card with ray tracing power and elite cooling.",
                "description": "A premium triple-fan GPU for 4K gaming, rendering, and streaming, finished with a reinforced backplate and black-and-gold showcase styling.",
                "price": "1199.00",
                "material": "16GB GDDR6X / PCIe 4.0",
                "stock": 8,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["memory"],
                "name": "Neo Fury DDR5 RGB RAM",
                "slug": "neo-fury-ddr5-rgb-ram",
                "tagline": "32GB low-latency DDR5 kit tuned for high-FPS gaming builds.",
                "description": "A 2x16GB performance memory kit with premium heat spreaders, stable XMP profiles, and warm gold lighting accents.",
                "price": "169.00",
                "material": "32GB / DDR5-6000 / CL30",
                "stock": 22,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1562976540-1502c2145186?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["processors"],
                "name": "Neo Ryzen 9 Apex CPU",
                "slug": "neo-ryzen-9-apex-cpu",
                "tagline": "16-core desktop processor for gaming, streaming, and rendering.",
                "description": "A high-end CPU selected for fast boost clocks, strong multicore output, and smooth performance in demanding PC builds.",
                "price": "549.00",
                "material": "16 Cores / 32 Threads",
                "stock": 14,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1555617981-dac3880eac6e?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["motherboards"],
                "name": "Neo X670E Carbon Board",
                "slug": "neo-x670e-carbon-board",
                "tagline": "ATX motherboard with PCIe 5.0, Wi-Fi 7, and premium VRM cooling.",
                "description": "A feature-rich board for enthusiast builds with reinforced slots, clean cable routing, and a polished black PCB.",
                "price": "429.00",
                "material": "ATX / PCIe 5.0 / Wi-Fi 7",
                "stock": 18,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["storage"],
                "name": "NeoSpeed Gen4 NVMe SSD",
                "slug": "neospeed-gen4-nvme-ssd",
                "tagline": "2TB NVMe drive for ultra-fast boot, game, and project loading.",
                "description": "A high-speed M.2 SSD with a slim heat spreader, strong sustained writes, and dependable performance for modern desktops.",
                "price": "189.00",
                "material": "2TB / PCIe Gen4 / M.2",
                "stock": 24,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoVolt 850W Gold PSU",
                "slug": "neovolt-850w-gold-psu",
                "tagline": "Modular 850W power supply with 80 Plus Gold efficiency.",
                "description": "A quiet, fully modular PSU designed for powerful GPUs, tidy cable management, and stable long-term performance.",
                "price": "159.00",
                "material": "850W / Fully Modular",
                "stock": 10,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["graphics_cards"],
                "name": "Neo RTX 4070 Ti Storm",
                "slug": "neo-rtx-4070-ti-storm",
                "tagline": "A balanced high-FPS GPU for 1440p ultra and smooth creator workflows.",
                "description": "A dual-BIOS graphics card with quiet fan curves, strong ray tracing performance, and a compact cooler for cleaner builds.",
                "price": "799.00",
                "material": "12GB GDDR6X / DLSS Ready",
                "stock": 16,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1616877564585-dc6816c892d2?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["memory"],
                "name": "Neo Stealth DDR5 64GB Kit",
                "slug": "neo-stealth-ddr5-64gb-kit",
                "tagline": "64GB capacity for streaming, editing, heavy multitasking, and premium gaming.",
                "description": "A 2x32GB DDR5 kit with low-profile heat spreaders, stable profiles, and understated black styling.",
                "price": "289.00",
                "material": "64GB / DDR5-5600 / CL36",
                "stock": 11,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1592664474496-8f0f7c3e7e7c?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["processors"],
                "name": "Neo Core i7 Turbo CPU",
                "slug": "neo-core-i7-turbo-cpu",
                "tagline": "Hybrid-core desktop processor for fast gaming and responsive workloads.",
                "description": "A powerful mainstream CPU for premium gaming builds, smooth streaming, and quick everyday performance.",
                "price": "389.00",
                "material": "20 Threads / Boost Clock",
                "stock": 19,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["motherboards"],
                "name": "Neo B650M Forge Board",
                "slug": "neo-b650m-forge-board",
                "tagline": "Compact motherboard with modern connectivity for clean micro-ATX builds.",
                "description": "A compact board with reinforced GPU slot, M.2 support, strong VRM cooling, and a tidy black layout.",
                "price": "219.00",
                "material": "mATX / DDR5 / M.2",
                "stock": 21,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1563770660941-10a63607739f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["storage"],
                "name": "NeoSpeed Gen5 NVMe SSD",
                "slug": "neospeed-gen5-nvme-ssd",
                "tagline": "Extreme-speed 1TB SSD for next-generation boot and load times.",
                "description": "A PCIe Gen5 M.2 drive with premium thermal control for compact, powerful desktop systems.",
                "price": "249.00",
                "material": "1TB / PCIe Gen5 / M.2",
                "stock": 15,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1628557118391-56cd62c9fcb6?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoChill 360 AIO Cooler",
                "slug": "neochill-360-aio-cooler",
                "tagline": "360mm liquid cooler with quiet fans and polished gold lighting accents.",
                "description": "A premium AIO liquid cooler for high-wattage CPUs, built with a large radiator, braided tubes, and clean pump lighting.",
                "price": "189.00",
                "material": "360mm / ARGB / PWM Fans",
                "stock": 13,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372162-587fba2ac20b?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoFlow 120mm Fan Pack",
                "slug": "neoflow-120mm-fan-pack",
                "tagline": "Triple fan kit for better airflow and subtle gold-tinted lighting.",
                "description": "A three-pack of quiet PWM fans with anti-vibration pads, daisy-chain wiring, and clean lighting control.",
                "price": "79.00",
                "material": "3 Pack / PWM / ARGB",
                "stock": 34,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "NeoGlass ATX Showcase Case",
                "slug": "neoglass-atx-showcase-case",
                "tagline": "Tempered-glass ATX case with panoramic visibility and strong airflow.",
                "description": "A premium case with mesh intake, glass side panel, PSU shroud, and generous routing space for clean cable work.",
                "price": "159.00",
                "material": "ATX / Tempered Glass",
                "stock": 12,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "NeoMini Airflow Case",
                "slug": "neomini-airflow-case",
                "tagline": "Compact case for powerful small-form builds with clean front ventilation.",
                "description": "A small-footprint case with smart internal layout, strong airflow, and support for modern compact gaming hardware.",
                "price": "119.00",
                "material": "Mini-ITX / Mesh / USB-C",
                "stock": 9,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["peripherals"],
                "name": "NeoKeys Pro Mechanical Keyboard",
                "slug": "neokeys-pro-mechanical-keyboard",
                "tagline": "Hot-swap mechanical keyboard with premium switches and metal frame.",
                "description": "A compact keyboard with responsive switches, dampened acoustics, and black-and-gold lighting for a polished setup.",
                "price": "139.00",
                "material": "75% / Hot-swap / RGB",
                "stock": 27,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["peripherals"],
                "name": "NeoView 27Q Gaming Monitor",
                "slug": "neoview-27q-gaming-monitor",
                "tagline": "27-inch QHD display with fast refresh for competitive and cinematic gaming.",
                "description": "A sharp QHD monitor with smooth motion, vivid color, slim bezels, and an elegant stand for premium desks.",
                "price": "329.00",
                "material": "27in / QHD / 180Hz",
                "stock": 18,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
            },
        ]

        for product in products:
            Product.objects.update_or_create(slug=product["slug"], defaults=product)

        self.stdout.write(self.style.SUCCESS("Seeded Neo China PC components catalog."))
