from django.core.management.base import BaseCommand

from shop.models import Category, Product


class Command(BaseCommand):
    help = "Seed the development database with premium PC component demo products."

    def handle(self, *args, **options):
        Product.objects.all().delete()
        Category.objects.all().delete()

        categories = {
            "graphics_cards": Category.objects.get_or_create(
                name="Graphics Cards",
                slug="graphics-cards",
                defaults={"description": "High-performance GPUs for gaming, rendering, and AI workloads."},
            )[0],
            "processors": Category.objects.get_or_create(
                name="Processors",
                slug="processors",
                defaults={"description": "Desktop CPUs for speed, efficiency, and multitasking."},
            )[0],
            "motherboards": Category.objects.get_or_create(
                name="Motherboards",
                slug="motherboards",
                defaults={"description": "Feature-rich boards with modern chipsets and expansion."},
            )[0],
            "storage": Category.objects.get_or_create(
                name="Storage",
                slug="storage",
                defaults={"description": "NVMe SSDs and drives for fast boot and load times."},
            )[0],
            "power_cooling": Category.objects.get_or_create(
                name="Power & Cooling",
                slug="power-cooling",
                defaults={"description": "Reliable PSUs, liquid coolers, and airflow essentials."},
            )[0],
            "cases": Category.objects.get_or_create(
                name="Cases",
                slug="cases",
                defaults={"description": "Showcase PC cases with airflow, glass, and clean cable paths."},
            )[0],
            "prebuilt_pcs": Category.objects.get_or_create(
                name="Prebuilt PCs",
                slug="prebuilt-pcs",
                defaults={"description": "Ready-to-ship gaming, creator, and workstation PCs with premium component pairings."},
            )[0],
            "peripherals": Category.objects.get_or_create(
                name="Peripherals",
                slug="peripherals",
                defaults={"description": "Keyboards, mice, monitors, and build-ready desk gear."},
            )[0],
            "lighting": Category.objects.get_or_create(
                name="RGB Lighting",
                slug="rgb-lighting",
                defaults={"description": "Light strips, controllers, and ARGB upgrades for showcase builds."},
            )[0],
            "gadgets": Category.objects.get_or_create(
                name="Gadgets",
                slug="gadgets",
                defaults={"description": "Useful desk gadgets and builder tools for PC setups."},
            )[0],
            "keyboards": Category.objects.get_or_create(
                name="Designer Keyboards",
                slug="designer-keyboards",
                defaults={"description": "Premium mechanical keyboards with tuned acoustics and luxury finishes."},
            )[0],
            "mice": Category.objects.get_or_create(
                name="Gaming Mice",
                slug="gaming-mice",
                defaults={"description": "Lightweight wireless mice for competitive and creator setups."},
            )[0],
            "audio_gear": Category.objects.get_or_create(
                name="Audio Gear",
                slug="audio-gear",
                defaults={"description": "IEMs, headphones, microphones, and headsets for gaming and streaming."},
            )[0],
        }

        products = [
            {
                "category": categories["graphics_cards"],
                "name": "Neo RTX 4080 Dragon OC",
                "slug": "neo-rtx-4080-dragon-oc",
                "tagline": "16GB GDDR6X graphics card with ray tracing power and elite cooling.",
                "description": "A premium triple-fan GPU for 4K gaming, rendering, and streaming, finished with a reinforced backplate and black-and-gold showcase styling.",
                "price": "1199.00",
                "material": "16GB GDDR6X / PCIe 4.0",
                "stock": 8,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["processors"],
                "name": "Neo Ryzen 9 Apex CPU",
                "slug": "neo-ryzen-9-apex-cpu",
                "tagline": "16-core desktop processor for gaming, streaming, and rendering.",
                "description": "A high-end CPU selected for fast boost clocks, strong multicore output, and smooth performance in demanding PC builds.",
                "price": "549.00",
                "material": "16 Cores / 32 Threads",
                "stock": 14,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1555617981-dac3880eac6e?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["motherboards"],
                "name": "Neo X670E Carbon Board",
                "slug": "neo-x670e-carbon-board",
                "tagline": "ATX motherboard with PCIe 5.0, Wi-Fi 7, and premium VRM cooling.",
                "description": "A feature-rich board for enthusiast builds with reinforced slots, clean cable routing, and a polished black PCB.",
                "price": "429.00",
                "material": "ATX / PCIe 5.0 / Wi-Fi 7",
                "stock": 18,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["storage"],
                "name": "NeoSpeed Gen4 NVMe SSD",
                "slug": "neospeed-gen4-nvme-ssd",
                "tagline": "2TB NVMe drive for ultra-fast boot, game, and project loading.",
                "description": "A high-speed M.2 SSD with a slim heat spreader, strong sustained writes, and dependable performance for modern desktops.",
                "price": "189.00",
                "material": "2TB / PCIe Gen4 / M.2",
                "stock": 24,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoVolt 850W Gold PSU",
                "slug": "neovolt-850w-gold-psu",
                "tagline": "Modular 850W power supply with 80 Plus Gold efficiency.",
                "description": "A quiet, fully modular PSU designed for powerful GPUs, tidy cable management, and stable long-term performance.",
                "price": "159.00",
                "material": "850W / Fully Modular",
                "stock": 10,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["graphics_cards"],
                "name": "Neo RTX 4070 Ti Storm",
                "slug": "neo-rtx-4070-ti-storm",
                "tagline": "A balanced high-FPS GPU for 1440p ultra and smooth creator workflows.",
                "description": "A dual-BIOS graphics card with quiet fan curves, strong ray tracing performance, and a compact cooler for cleaner builds.",
                "price": "799.00",
                "material": "12GB GDDR6X / DLSS Ready",
                "stock": 16,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["processors"],
                "name": "Neo Core i7 Turbo CPU",
                "slug": "neo-core-i7-turbo-cpu",
                "tagline": "Hybrid-core desktop processor for fast gaming and responsive workloads.",
                "description": "A powerful mainstream CPU for premium gaming builds, smooth streaming, and quick everyday performance.",
                "price": "389.00",
                "material": "20 Threads / Boost Clock",
                "stock": 19,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["motherboards"],
                "name": "Neo B650M Forge Board",
                "slug": "neo-b650m-forge-board",
                "tagline": "Compact motherboard with modern connectivity for clean micro-ATX builds.",
                "description": "A compact board with reinforced GPU slot, M.2 support, strong VRM cooling, and a tidy black layout.",
                "price": "219.00",
                "material": "mATX / DDR5 / M.2",
                "stock": 21,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1563770660941-10a63607739f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["storage"],
                "name": "NeoSpeed Gen5 NVMe SSD",
                "slug": "neospeed-gen5-nvme-ssd",
                "tagline": "Extreme-speed 1TB SSD for next-generation boot and load times.",
                "description": "A PCIe Gen5 M.2 drive with premium thermal control for compact, powerful desktop systems.",
                "price": "249.00",
                "material": "1TB / PCIe Gen5 / M.2",
                "stock": 15,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoChill 360 AIO Cooler",
                "slug": "neochill-360-aio-cooler",
                "tagline": "360mm liquid cooler with quiet fans and polished gold lighting accents.",
                "description": "A premium AIO liquid cooler for high-wattage CPUs, built with a large radiator, braided tubes, and clean pump lighting.",
                "price": "189.00",
                "material": "360mm / ARGB / PWM Fans",
                "stock": 13,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["power_cooling"],
                "name": "NeoFlow 120mm Fan Pack",
                "slug": "neoflow-120mm-fan-pack",
                "tagline": "Triple fan kit for better airflow and subtle gold-tinted lighting.",
                "description": "A three-pack of quiet PWM fans with anti-vibration pads, daisy-chain wiring, and clean lighting control.",
                "price": "79.00",
                "material": "3 Pack / PWM / ARGB",
                "stock": 34,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "NeoGlass ATX Showcase Case",
                "slug": "neoglass-atx-showcase-case",
                "tagline": "Tempered-glass ATX case with panoramic visibility and strong airflow.",
                "description": "A premium case with mesh intake, glass side panel, PSU shroud, and generous routing space for clean cable work.",
                "price": "159.00",
                "material": "ATX / Tempered Glass",
                "stock": 12,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "NeoMini Airflow Case",
                "slug": "neomini-airflow-case",
                "tagline": "Compact case for powerful small-form builds with clean front ventilation.",
                "description": "A small-footprint case with smart internal layout, strong airflow, and support for modern compact gaming hardware.",
                "price": "119.00",
                "material": "Mini-ITX / Mesh / USB-C",
                "stock": 9,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["peripherals"],
                "name": "NeoKeys Pro Mechanical Keyboard",
                "slug": "neokeys-pro-mechanical-keyboard",
                "tagline": "Hot-swap mechanical keyboard with premium switches and metal frame.",
                "description": "A compact keyboard with responsive switches, dampened acoustics, and black-and-gold lighting for a polished setup.",
                "price": "139.00",
                "material": "75% / Hot-swap / RGB",
                "stock": 27,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["peripherals"],
                "name": "NeoView 27Q Gaming Monitor",
                "slug": "neoview-27q-gaming-monitor",
                "tagline": "27-inch QHD display with fast refresh for competitive and cinematic gaming.",
                "description": "A sharp QHD monitor with smooth motion, vivid color, slim bezels, and an elegant stand for premium desks.",
                "price": "329.00",
                "material": "27in / QHD / 180Hz",
                "stock": 18,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["lighting"],
                "name": "NeoGlow ARGB Light Bars",
                "slug": "neoglow-argb-light-bars",
                "tagline": "Magnetic light bars for clean internal case glow and build highlights.",
                "description": "A pair of slim ARGB bars with magnetic mounts, diffuser lenses, and motherboard sync support for premium showcase PCs.",
                "price": "49.00",
                "material": "2 Pack / ARGB / Magnetic",
                "stock": 38,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1603481546579-65d935ba9cdd?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["lighting"],
                "name": "NeoSync RGB Controller Hub",
                "slug": "neosync-rgb-controller-hub",
                "tagline": "Central control for fans, light strips, and synchronized RGB effects.",
                "description": "A compact hub for managing ARGB devices with clean cable routing, multiple lighting channels, and software sync support.",
                "price": "39.00",
                "material": "8 Port / ARGB / PWM",
                "stock": 41,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["lighting"],
                "name": "NeoLine RGB Cable Extensions",
                "slug": "neoline-rgb-cable-extensions",
                "tagline": "Premium PSU cable extensions with a soft gold RGB accent line.",
                "description": "Sleeved extension cables for 24-pin motherboard and GPU power, made for cleaner builds and color-matched lighting.",
                "price": "69.00",
                "material": "24-pin / GPU / ARGB",
                "stock": 26,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["gadgets"],
                "name": "NeoDesk USB-C Dock",
                "slug": "neodesk-usb-c-dock",
                "tagline": "Compact desk dock with display, USB, Ethernet, and fast power passthrough.",
                "description": "A clean aluminum docking station for gaming desks, creator setups, and laptop-to-desktop workflows.",
                "price": "129.00",
                "material": "USB-C / HDMI / 100W PD",
                "stock": 20,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1615526675159-e248c3021d3f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["gadgets"],
                "name": "NeoTool Precision Builder Kit",
                "slug": "neotool-precision-builder-kit",
                "tagline": "A compact toolkit for PC assembly, upgrades, and maintenance.",
                "description": "Includes precision bits, anti-static tools, cable ties, pry tools, and a magnetic tray for smoother PC building.",
                "price": "59.00",
                "material": "48-piece / Anti-static",
                "stock": 32,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["gadgets"],
                "name": "NeoTemp Smart Display",
                "slug": "neotemp-smart-display",
                "tagline": "Mini status screen for CPU, GPU, storage, and system temperature readouts.",
                "description": "A compact desktop or case-mounted display for monitoring performance stats with a clean black-and-gold interface.",
                "price": "89.00",
                "material": "3.5in IPS / USB",
                "stock": 17,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["peripherals"],
                "name": "NeoStrike Wireless Mouse",
                "slug": "neostrike-wireless-mouse",
                "tagline": "Lightweight wireless gaming mouse with fast sensor tracking.",
                "description": "A low-latency mouse with precise tracking, long battery life, and subtle gold lighting for matching setups.",
                "price": "99.00",
                "material": "26K DPI / Wireless",
                "stock": 29,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["storage"],
                "name": "NeoArchive 4TB HDD",
                "slug": "neoarchive-4tb-hdd",
                "tagline": "High-capacity storage for game libraries, media, and project archives.",
                "description": "A reliable desktop hard drive for builders who need affordable bulk storage beside a fast NVMe boot drive.",
                "price": "109.00",
                "material": "4TB / 7200RPM / SATA",
                "stock": 23,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "NeoType Imperial 75 Keyboard",
                "slug": "neotype-imperial-75-keyboard",
                "tagline": "Designer 75% mechanical keyboard with gasket mount and premium gold accents.",
                "description": "A luxury keyboard with a CNC-style frame, tuned stabilizers, hot-swap PCB, and warm backlighting for refined desks.",
                "price": "249.00",
                "material": "75% / Gasket / Hot-swap",
                "stock": 18,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "KeyForge Jade Pro TKL",
                "slug": "keyforge-jade-pro-tkl",
                "tagline": "Branded TKL board with soft tactile switches and double-shot keycaps.",
                "description": "A clean tenkeyless keyboard made for gaming and typing, with dampened internals and a black-and-gold desk presence.",
                "price": "189.00",
                "material": "TKL / Tactile / PBT",
                "stock": 24,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "LuxeBoard Phantom 65",
                "slug": "luxeboard-phantom-65",
                "tagline": "Compact designer keyboard with aluminum shell and creamy linear switches.",
                "description": "A 65% enthusiast board with a polished weight, foam-tuned sound, and compact layout for premium gaming setups.",
                "price": "219.00",
                "material": "65% / Aluminum / Linear",
                "stock": 16,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "NeoType Creator Full Size",
                "slug": "neotype-creator-full-size",
                "tagline": "Full-size keyboard for editing, spreadsheets, and premium workstation builds.",
                "description": "A refined full-size board with media controls, quiet switches, and a black frame that pairs well with gold lighting.",
                "price": "159.00",
                "material": "Full Size / Silent / RGB",
                "stock": 20,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["mice"],
                "name": "NeoStrike Viper Wireless",
                "slug": "neostrike-viper-wireless",
                "tagline": "Ultra-light wireless mouse with flagship sensor and fast charging dock.",
                "description": "A competitive gaming mouse with low-latency wireless, crisp switches, textured side grip, and subtle gold lighting.",
                "price": "129.00",
                "material": "49g / 30K DPI / Wireless",
                "stock": 31,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["mice"],
                "name": "DragonClaw MMO Elite Mouse",
                "slug": "dragonclaw-mmo-elite-mouse",
                "tagline": "Multi-button gaming mouse for MMOs, productivity macros, and streaming controls.",
                "description": "A sculpted performance mouse with programmable side buttons, adjustable DPI, and a premium braided cable.",
                "price": "89.00",
                "material": "12 Buttons / 19K DPI",
                "stock": 27,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["mice"],
                "name": "NeoGlide Glass Mousepad",
                "slug": "neoglide-glass-mousepad",
                "tagline": "Premium glass surface for smooth tracking and a sharp desktop finish.",
                "description": "A hard-surface mousepad with rounded edges, non-slip base, and low-friction glide for fast aim control.",
                "price": "79.00",
                "material": "Glass / XL / Low Friction",
                "stock": 33,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "NeoSound Atlas IEMs",
                "slug": "neosound-atlas-iems",
                "tagline": "Dual-driver IEMs tuned for gaming detail, music clarity, and long sessions.",
                "description": "Premium in-ear monitors with detachable cable, metal shells, balanced sound, and a compact carry case.",
                "price": "119.00",
                "material": "Dual Driver / Detachable Cable",
                "stock": 28,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "Auralux Studio Headphones",
                "slug": "auralux-studio-headphones",
                "tagline": "Closed-back headphones for gaming, editing, and focused listening.",
                "description": "A comfortable over-ear headset with detailed mids, controlled bass, plush pads, and premium black-and-gold trim.",
                "price": "179.00",
                "material": "Closed Back / 50mm Driver",
                "stock": 22,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "NeoComms Wireless Gaming Headset",
                "slug": "neocomms-wireless-gaming-headset",
                "tagline": "Low-latency wireless headset with detachable mic and spatial sound.",
                "description": "Built for competitive play and streaming with breathable cushions, long battery life, and clear voice pickup.",
                "price": "149.00",
                "material": "2.4GHz / Spatial / Detachable Mic",
                "stock": 25,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1599669454699-248893623440?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "NeoCast Pro USB Microphone",
                "slug": "neocast-pro-usb-microphone",
                "tagline": "Broadcast-style USB microphone for streaming, calls, and content creation.",
                "description": "A desk-ready mic with gain control, tap mute, headphone monitoring, and a warm vocal profile.",
                "price": "129.00",
                "material": "USB-C / Cardioid / Mute",
                "stock": 19,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "NeoDAC Mini Audio Interface",
                "slug": "neodac-mini-audio-interface",
                "tagline": "Compact DAC/amp for cleaner headphone output and desk audio control.",
                "description": "A small desktop audio upgrade with precise volume control, low-noise output, and a refined metal body.",
                "price": "99.00",
                "material": "DAC / Amp / USB-C",
                "stock": 21,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1558089687-f282ffcbc126?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Dragonfire X9",
                "slug": "neo-dragonfire-x9",
                "tagline": "Flagship 4K gaming tower with RTX 4090-class power and liquid cooling.",
                "description": "A showcase prebuilt PC with a panoramic glass case, synchronized gold lighting, premium cable work, and elite thermal headroom for max-settings gaming.",
                "price": "3999.00",
                "material": "RTX 4090 / Ryzen 9 / 64GB memory",
                "stock": 4,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Phantom Creator Pro",
                "slug": "neo-phantom-creator-pro",
                "tagline": "Creator workstation tuned for editing, 3D rendering, streaming, and AI workloads.",
                "description": "A quiet black-and-gold workstation with high-core CPU performance, studio-ready storage, and a refined airflow layout for long render sessions.",
                "price": "3299.00",
                "material": "RTX 4080 / Core i9 / 4TB NVMe",
                "stock": 6,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Eclipse 4070",
                "slug": "neo-eclipse-4070",
                "tagline": "Premium 1440p gaming PC with clean glass styling and balanced performance.",
                "description": "A polished mid-tower build for high-refresh gaming, content work, and daily productivity with strong airflow and tidy internal lighting.",
                "price": "1899.00",
                "material": "RTX 4070 / Ryzen 7 / 32GB memory",
                "stock": 9,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1593640408182-31c70c8268f5?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Lunar Mini",
                "slug": "neo-lunar-mini",
                "tagline": "Compact small-form PC with serious gaming power and quiet cooling.",
                "description": "A space-saving prebuilt for premium desks, dorms, and studio setups, designed with mesh airflow and understated lighting.",
                "price": "1499.00",
                "material": "RTX 4060 Ti / Ryzen 5 / 1TB NVMe",
                "stock": 8,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Titan Workstation",
                "slug": "neo-titan-workstation",
                "tagline": "Heavy-duty workstation for CAD, simulation, rendering, and multitasking.",
                "description": "Built around workstation-grade stability, generous memory, high-capacity storage, and a quiet professional chassis.",
                "price": "4599.00",
                "material": "RTX Ada / Threadripper / 128GB ECC",
                "stock": 3,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Mirage StreamBox",
                "slug": "neo-mirage-streambox",
                "tagline": "Streaming-ready PC with capture-friendly performance and low-noise cooling.",
                "description": "A sleek creator tower for gameplay, streaming, recording, and editing with a warm gold glow and broadcast-ready performance.",
                "price": "2299.00",
                "material": "RTX 4070 Ti / Core i7 / 2TB NVMe",
                "stock": 7,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Obsidian Starter",
                "slug": "neo-obsidian-starter",
                "tagline": "Entry gaming PC with premium looks, upgrade room, and dependable parts.",
                "description": "A clean first gaming PC with a modern GPU, fast SSD, reliable PSU, and a case layout that makes future upgrades easy.",
                "price": "999.00",
                "material": "RTX 4060 / Ryzen 5 / 16GB memory",
                "stock": 12,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1593640495253-23196b27a87f?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Halo White Edition",
                "slug": "neo-halo-white-edition",
                "tagline": "Designer white-and-gold prebuilt made for showcase desks and creator rooms.",
                "description": "A limited aesthetic build with bright tempered glass styling, quiet fans, clean cable routing, and a premium component stack.",
                "price": "2499.00",
                "material": "RTX 4070 Super / Ryzen 7 / 32GB memory",
                "stock": 5,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Stealth Gamer S5",
                "slug": "neo-stealth-gamer-s5",
                "tagline": "Minimalist dark chassis with powerful mid-range gaming performance.",
                "description": "A compact black tower built for 1080p and 1440p gameplay, with efficient cooling and premium cable management.",
                "price": "1699.00",
                "material": "RTX 4060 Ti / Ryzen 5 / 16GB memory",
                "stock": 11,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Arc Studio 16",
                "slug": "neo-arc-studio-16",
                "tagline": "Creator-focused workstation with fast storage and quiet performance.",
                "description": "A refined build for streaming, editing, and creative workflows, featuring a balanced GPU and high-speed NVMe storage.",
                "price": "2799.00",
                "material": "RTX 4070 Super / Ryzen 9 / 64GB memory",
                "stock": 6,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["prebuilt_pcs"],
                "name": "Neo Rift Elite",
                "slug": "neo-rift-elite",
                "tagline": "Elite desktop for high refresh gaming, streaming, and advanced multitasking.",
                "description": "A top-tier system with premium airflow, premium components, and aggressive styling for showcase rigs.",
                "price": "3599.00",
                "material": "RTX 4080 Ti / Core i9 / 64GB memory",
                "stock": 4,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "NeoVault Pro XL Cabinet",
                "slug": "neovault-pro-xl-cabinet",
                "tagline": "Full-tower PC cabinet with dual-chamber layout and premium showcase glass.",
                "description": "A large-format cabinet for extreme builds with hidden cable routing, vertical GPU support, and quiet airflow channels.",
                "price": "249.00",
                "material": "E-ATX / Dual Chamber / Glass",
                "stock": 10,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1587202372616-b43abea06c2a?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "DragonShell Mesh Cabinet",
                "slug": "dragonshell-mesh-cabinet",
                "tagline": "Airflow-first gaming cabinet with bold front mesh and gold lighting trim.",
                "description": "A performance cabinet made for hot GPUs, with wide intake mesh, tool-free panels, and clean black internal finishing.",
                "price": "139.00",
                "material": "ATX / Mesh / USB-C",
                "stock": 18,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1587202372634-32705e3bf49c?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["cases"],
                "name": "LuxeFrame Curve Cabinet",
                "slug": "luxeframe-curve-cabinet",
                "tagline": "Designer curved-glass cabinet for premium display builds.",
                "description": "A sleek cabinet with curved glass, hidden PSU bay, ARGB fan support, and a clean exhibition-style interior.",
                "price": "199.00",
                "material": "ATX / Curved Glass / ARGB",
                "stock": 14,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1624705002806-5d72df19c3ad?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "RavenKey Carbon Alice",
                "slug": "ravenkey-carbon-alice",
                "tagline": "Designer ergonomic keyboard with split Alice layout and carbon black finish.",
                "description": "A boutique-style keyboard with hot-swap switches, tuned foam layers, PBT keycaps, and a premium typing angle.",
                "price": "279.00",
                "material": "Alice / Hot-swap / PBT",
                "stock": 12,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["keyboards"],
                "name": "Kronos LowPro Wireless",
                "slug": "kronos-lowpro-wireless",
                "tagline": "Slim wireless mechanical keyboard for premium work and gaming desks.",
                "description": "A low-profile board with multi-device wireless, aluminum top plate, and clean warm backlighting.",
                "price": "169.00",
                "material": "Low Profile / Wireless / RGB",
                "stock": 26,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["mice"],
                "name": "RazorWing Pro 8K Mouse",
                "slug": "razorwing-pro-8k-mouse",
                "tagline": "Esports mouse with 8K polling and ultra-light shell.",
                "description": "A responsive branded-style mouse with crisp optical clicks, PTFE feet, and a sculpted body for fast aim control.",
                "price": "119.00",
                "material": "8K Polling / 46g / Wireless",
                "stock": 22,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["mice"],
                "name": "GoldPulse Creator Mouse",
                "slug": "goldpulse-creator-mouse",
                "tagline": "Productivity mouse with silent clicks, side scroll, and precise sensor tracking.",
                "description": "A premium creator mouse for editing timelines, spreadsheets, and multi-monitor workstations.",
                "price": "109.00",
                "material": "Silent / Side Scroll / Wireless",
                "stock": 25,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "SoundForge Crown IEM",
                "slug": "soundforge-crown-iem",
                "tagline": "Triple-driver IEMs for competitive detail and rich music playback.",
                "description": "A premium in-ear set with detachable braided cable, metal shells, and tuned imaging for footsteps and vocals.",
                "price": "159.00",
                "material": "Triple Driver / MMCX Cable",
                "stock": 24,
                "is_featured": True,
                "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=1200&q=80",
            },
            {
                "category": categories["audio_gear"],
                "name": "NeoBass Nova Headphones",
                "slug": "neobass-nova-headphones",
                "tagline": "Wireless headphones with deep bass, clean mic, and premium comfort.",
                "description": "A stylish over-ear headset with long battery life, low-latency mode, and plush cushions for daily gaming and music.",
                "price": "199.00",
                "material": "Wireless / ANC / 45hr Battery",
                "stock": 17,
                "is_featured": False,
                "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
            },
        ]

        for product in products:
            Product.objects.update_or_create(slug=product["slug"], defaults=product)

        self.stdout.write(self.style.SUCCESS("Seeded Neo China PC components catalog."))
